config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users, :controllers => { registrations: 'registrations', sessions: "sessions", omniauth_callbacks: "callbacks"}

  as :user do
    put 'users/:id' => 'registrations#update', :as => 'update_user'
    get 'users' => 'user#index', :as => 'users'
    get 'need_invite' => 'registrations#need_invite', :as => 'need_invite'
  end

  resources :user do
    resources :invitations, only: [:new, :create]
    get :autocomplete_location, :on => :collection
    get :autocomplete_organization, :on => :collection
  end

  root 'home#index'

end

app/views/layouts/_nav_menu.html.haml
%nav.top-bar{'data-topbar' => true, "role"=>"navigation"}
  %ul.title-area
    %li.name
      #loading_spinner
        = fa_icon "spinner", class: "fa-lg fa fa-spinner fa-pulse icon-big"
        
  %section.top-bar-section
    %ul.right
      - if user_signed_in?
        %li= link_to "Hi, #{current_user.name}!", '#'
        %li
          = link_to root_path do
            =fa_icon "home", class: "nav-icon fa-lg"
        %li{:title=>"Find people"}
          = link_to users_path do
            =fa_icon "user", class: "nav-icon fa-lg"
        %li{:title=>"Invite people"}
          =link_to new_user_invitation_path(current_user) do
            =fa_icon "plus", class: "nav-icon fa-lg"
        %li{:title=>"Edit your info"}
          =link_to edit_registration_path(current_user) do
            =fa_icon "gear", class: "nav-icon fa-lg"
        %li{:title=>"Log out"}
          =link_to destroy_user_session_path, method: :delete do
            =fa_icon "sign-out", class: "nav-icon fa-lg"
      - else
        %li= link_to "Login", new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title connect@ustksa
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
  %body
    .row#container
      =render "layouts/nav_menu"
      #content_container
        #flash_container.large-text-center
          - if flash[:notice]
            .notice.alert-box.info
              =simple_format(flash[:notice], {}, wrapper_tag: "span")
              %a.close(href="#") &times;
          - if flash[:error]
            .alert.alert-box
              =simple_format(flash[:error])
              %a.close(href="#") &times;
          - if flash[:alert]
            .alert.alert-box
              =simple_format(flash[:alert], {}, wrapper_tag: "span")
              %a.close(href="#") &times;
        #content
          =yield